import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Command, Container, Cpu, TerminalSquare } from "lucide-react";

const frameworks = [["React", "/react.svg"], ["Next.js", "/nextjs-icon.svg"], ["Vue", "/vuejs-icon.svg"], ["Angular", "/angular-2.svg"], ["Express", "/expressjs-icon.svg"], ["Hono", "/hono.svg"]];
const features = [[Cpu,"Monaco intelligence","Fast editing, diagnostics, multi-file tabs, and AI-assisted suggestions."],[Container,"Isolated runtime","Install dependencies and run servers directly in the browser."],[TerminalSquare,"Developer workflow","Integrated terminal, live preview, device modes, and runtime status."],[Command,"Keyboard first","Command palette and quick file open keep the workspace moving."],[Check,"Six templates","React, Next.js, Vue, Angular, Express, and Hono are ready to start."],[ArrowRight,"Understandable code","Focused components extend the existing architecture without replacing it."]] as const;
export default function Home() {
  return <div className="landing-grid bg-[#09090b] text-zinc-100">
    <section className="mx-auto flex min-h-[calc(100vh-3.5rem)] max-w-7xl flex-col items-center px-4 pt-16 text-center sm:pt-20"><p className="mb-5 border border-red-500/30 bg-red-500/10 px-3 py-1 text-[11px] font-medium text-red-300">BROWSER IDE · ZERO LOCAL SETUP</p><h1 className="max-w-4xl text-5xl font-bold leading-[1.06] sm:text-7xl">VibeCode Editor</h1><p className="mt-5 max-w-2xl text-base leading-7 text-zinc-400">Build, run, and preview complete web projects in one focused workspace. Your files, editor, terminal, and live server stay together.</p><div className="mt-7 flex gap-3"><Link href="/dashboard" className="flex items-center gap-2 rounded-sm bg-[#e23d57] px-5 py-3 text-sm font-semibold text-white hover:bg-[#f04b64]">Start coding <ArrowRight size={15} /></Link><Link href="/docs" className="rounded-sm border border-white/15 px-5 py-3 text-sm hover:bg-white/5">Read docs</Link></div>
      <div className="mt-12 w-full overflow-hidden rounded-md border border-white/15 bg-[#111318] text-left shadow-2xl shadow-black/50"><div className="flex h-10 items-center border-b border-white/10 px-3 text-[11px] text-zinc-500"><span className="text-red-400">●</span><span className="ml-3 text-zinc-300">vibecode / app</span><span className="mx-auto hidden rounded-sm border border-white/10 bg-black/20 px-16 py-1 sm:block">Search commands or files</span><span>Run ▶</span></div><div className="grid h-[380px] grid-cols-[42px_180px_1fr] sm:grid-cols-[42px_220px_1fr_34%]"><div className="border-r border-white/10 py-3 text-center text-zinc-500"><div className="border-l-2 border-red-500 py-3 text-zinc-100">□</div><div className="py-3">⌕</div><div className="py-3">▷</div></div><div className="border-r border-white/10 p-3 text-xs text-zinc-500"><p className="mb-4 text-[10px] font-bold text-zinc-300">EXPLORER</p><p>⌄ src</p><p className="py-1 pl-4 text-red-300">◇ App.tsx</p><p className="py-1 pl-4"># styles.css</p><p className="py-1">{} package.json</p></div><div className="min-w-0 bg-[#0b0d10] font-mono text-xs"><div className="border-b border-white/10 px-4 py-3 text-zinc-300">App.tsx <span className="text-red-400">●</span></div><pre className="overflow-hidden p-5 leading-7 text-zinc-400"><span className="text-pink-400">export default function</span> <span className="text-amber-200">App</span>() {`{`}\n  <span className="text-pink-400">return</span> (\n    &lt;<span className="text-red-300">Workspace</span> status=<span className="text-emerald-300">&quot;ready&quot;</span> /&gt;\n  )\n{`}`}</pre></div><div className="hidden border-l border-white/10 bg-white sm:block"><div className="h-9 bg-[#16181d] px-3 py-2 text-[10px] text-zinc-400">● Ready · localhost:3000</div><div className="flex h-[calc(100%-2.25rem)] items-center justify-center bg-zinc-50 text-zinc-900"><div className="text-center"><Image src="/logo.svg" alt="VibeCode preview" width={64} height={64} className="mx-auto" /><strong>Ship the idea.</strong><p className="mt-2 text-xs text-zinc-500">Your preview is live.</p></div></div></div></div><div className="flex h-6 items-center bg-[#c9344c] px-3 text-[10px]">main* <span className="ml-auto">TypeScript · Ln 8, Col 14 · Node 20 · ● Ready</span></div></div>
    </section>
    <section id="templates" className="border-y border-white/10 bg-[#0b0d10] px-4 py-14"><p className="text-center text-xs text-zinc-500">START WITH THE STACK YOU KNOW</p><div className="mx-auto mt-8 grid max-w-5xl grid-cols-3 gap-px border border-white/10 bg-white/10 sm:grid-cols-6">{frameworks.map(([name, src]) => <div key={name} className="flex items-center justify-center gap-2 bg-[#111318] px-4 py-5 text-xs"><Image src={src} alt="" width={22} height={22} />{name}</div>)}</div></section>
    <section id="features" className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-px overflow-hidden rounded-md border border-white/10 bg-white/10 md:grid-cols-3">{features.map(([Icon,title,copy]) => <article key={title} className="bg-[#111318] p-7"><Icon size={20} className="text-red-400"/><h2 className="mt-5 text-sm font-semibold">{title}</h2><p className="mt-3 text-xs leading-6 text-zinc-500">{copy}</p></article>)}</div></section>
    <section className="border-t border-white/10 px-6 py-24 text-center"><h2 className="text-3xl font-bold">Ready to build?</h2><p className="mx-auto mt-3 max-w-lg text-sm text-zinc-400">Launch a complete development workspace directly in your browser.</p><div className="mt-7 flex justify-center gap-3"><Link href="/dashboard" className="bg-[#e23d57] px-5 py-3 text-sm font-semibold">Start coding</Link><Link href="https://github.com/BRaj-05/Code-Editor" className="border border-white/15 px-5 py-3 text-sm">View GitHub</Link></div></section>
  </div>;
}
